repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      # проверяет наличие переноса строки в конце всех текстовых файлов
      - id: end-of-file-fixer
      # предупреждает о добавлении больших файлов в Git
      - id: check-added-large-files
      # предупреждает о сохранении файлов с UTF-8 BOM
      - id: check-byte-order-marker
      # предотвращает сохранение приватных ключей
      - id: detect-private-key
      # проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python
      - id: check-ast
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args:
          - --max-line-length=120
        exclude: ./migrations/

      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]

      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        args:
          - --line-length=120

      - id: mypy
        name: mypy
        entry: mypy .
        pass_filenames: false
        language: system
        types: [ python ]
        require_serial: false
